begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * This file is subject to the license found in LICENCE.TXT in the root directory of the project.  *   * #SNAPSHOT#  */
end_comment

begin_package
package|package
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|ant
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|BufferedReader
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|FileReader
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tools
operator|.
name|ant
operator|.
name|Project
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tools
operator|.
name|ant
operator|.
name|taskdefs
operator|.
name|Delete
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|DependencyDescriptor
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|Ivy
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|ModuleDescriptor
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|ModuleRevisionId
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|util
operator|.
name|FileUtil
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|xml
operator|.
name|XmlModuleDescriptorParser
import|;
end_import

begin_class
specifier|public
class|class
name|IvyDeliverTest
extends|extends
name|TestCase
block|{
specifier|private
name|File
name|_cache
decl_stmt|;
specifier|private
name|IvyDeliver
name|_deliver
decl_stmt|;
specifier|private
name|Project
name|_project
decl_stmt|;
specifier|protected
name|void
name|setUp
parameter_list|()
throws|throws
name|Exception
block|{
name|cleanTestDir
argument_list|()
expr_stmt|;
name|cleanRep
argument_list|()
expr_stmt|;
name|createCache
argument_list|()
expr_stmt|;
name|_project
operator|=
operator|new
name|Project
argument_list|()
expr_stmt|;
name|_project
operator|.
name|setProperty
argument_list|(
literal|"ivy.conf.file"
argument_list|,
literal|"test/repositories/ivyconf.xml"
argument_list|)
expr_stmt|;
name|_project
operator|.
name|setProperty
argument_list|(
literal|"build"
argument_list|,
literal|"build/test/deliver"
argument_list|)
expr_stmt|;
name|_deliver
operator|=
operator|new
name|IvyDeliver
argument_list|()
expr_stmt|;
name|_deliver
operator|.
name|setProject
argument_list|(
name|_project
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|setCache
argument_list|(
name|_cache
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|createCache
parameter_list|()
block|{
name|_cache
operator|=
operator|new
name|File
argument_list|(
literal|"build/cache"
argument_list|)
expr_stmt|;
name|_cache
operator|.
name|mkdirs
argument_list|()
expr_stmt|;
block|}
specifier|protected
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{
name|cleanCache
argument_list|()
expr_stmt|;
name|cleanTestDir
argument_list|()
expr_stmt|;
name|cleanRep
argument_list|()
expr_stmt|;
block|}
specifier|private
name|void
name|cleanCache
parameter_list|()
block|{
name|Delete
name|del
init|=
operator|new
name|Delete
argument_list|()
decl_stmt|;
name|del
operator|.
name|setProject
argument_list|(
operator|new
name|Project
argument_list|()
argument_list|)
expr_stmt|;
name|del
operator|.
name|setDir
argument_list|(
name|_cache
argument_list|)
expr_stmt|;
name|del
operator|.
name|execute
argument_list|()
expr_stmt|;
block|}
specifier|private
name|void
name|cleanTestDir
parameter_list|()
block|{
name|Delete
name|del
init|=
operator|new
name|Delete
argument_list|()
decl_stmt|;
name|del
operator|.
name|setProject
argument_list|(
operator|new
name|Project
argument_list|()
argument_list|)
expr_stmt|;
name|del
operator|.
name|setDir
argument_list|(
operator|new
name|File
argument_list|(
literal|"build/test/deliver"
argument_list|)
argument_list|)
expr_stmt|;
name|del
operator|.
name|execute
argument_list|()
expr_stmt|;
block|}
specifier|private
name|void
name|cleanRep
parameter_list|()
block|{
name|Delete
name|del
init|=
operator|new
name|Delete
argument_list|()
decl_stmt|;
name|del
operator|.
name|setProject
argument_list|(
operator|new
name|Project
argument_list|()
argument_list|)
expr_stmt|;
name|del
operator|.
name|setDir
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/repositories/1/jayasoft"
argument_list|)
argument_list|)
expr_stmt|;
name|del
operator|.
name|execute
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testSimple
parameter_list|()
throws|throws
name|Exception
block|{
name|_project
operator|.
name|setProperty
argument_list|(
literal|"ivy.dep.file"
argument_list|,
literal|"test/java/fr/jayasoft/ivy/ant/ivy-latest.xml"
argument_list|)
expr_stmt|;
name|IvyResolve
name|res
init|=
operator|new
name|IvyResolve
argument_list|()
decl_stmt|;
name|res
operator|.
name|setProject
argument_list|(
name|_project
argument_list|)
expr_stmt|;
name|res
operator|.
name|execute
argument_list|()
expr_stmt|;
name|_deliver
operator|.
name|setPubrevision
argument_list|(
literal|"1.2"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|setDeliverpattern
argument_list|(
literal|"build/test/deliver/ivy-[revision].xml"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// should have done the ivy delivering
name|File
name|deliveredIvyFile
init|=
operator|new
name|File
argument_list|(
literal|"build/test/deliver/ivy-1.2.xml"
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|deliveredIvyFile
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|ModuleDescriptor
name|md
init|=
name|XmlModuleDescriptorParser
operator|.
name|getInstance
argument_list|()
operator|.
name|parseDescriptor
argument_list|(
operator|new
name|Ivy
argument_list|()
argument_list|,
name|deliveredIvyFile
operator|.
name|toURL
argument_list|()
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"jayasoft"
argument_list|,
literal|"resolve-latest"
argument_list|,
literal|"1.2"
argument_list|)
argument_list|,
name|md
operator|.
name|getModuleRevisionId
argument_list|()
argument_list|)
expr_stmt|;
name|DependencyDescriptor
index|[]
name|dds
init|=
name|md
operator|.
name|getDependencies
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|dds
operator|.
name|length
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.2"
argument_list|)
argument_list|,
name|dds
index|[
literal|0
index|]
operator|.
name|getDependencyRevisionId
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testReplaceImportedConfigurations
parameter_list|()
throws|throws
name|Exception
block|{
name|_project
operator|.
name|setProperty
argument_list|(
literal|"ivy.dep.file"
argument_list|,
literal|"test/java/fr/jayasoft/ivy/ant/ivy-import-confs.xml"
argument_list|)
expr_stmt|;
name|IvyResolve
name|res
init|=
operator|new
name|IvyResolve
argument_list|()
decl_stmt|;
name|res
operator|.
name|setProject
argument_list|(
name|_project
argument_list|)
expr_stmt|;
name|res
operator|.
name|execute
argument_list|()
expr_stmt|;
name|_deliver
operator|.
name|setPubrevision
argument_list|(
literal|"1.2"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|setDeliverpattern
argument_list|(
literal|"build/test/deliver/ivy-[revision].xml"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// should have done the ivy delivering
name|File
name|deliveredIvyFile
init|=
operator|new
name|File
argument_list|(
literal|"build/test/deliver/ivy-1.2.xml"
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|deliveredIvyFile
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|String
name|deliveredFileContent
init|=
name|FileUtil
operator|.
name|readEntirely
argument_list|(
operator|new
name|BufferedReader
argument_list|(
operator|new
name|FileReader
argument_list|(
name|deliveredIvyFile
argument_list|)
argument_list|)
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"import not replaced: import can still be found in file"
argument_list|,
name|deliveredFileContent
operator|.
name|indexOf
argument_list|(
literal|"import"
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
literal|"import not replaced: conf1 cannot be found in file"
argument_list|,
name|deliveredFileContent
operator|.
name|indexOf
argument_list|(
literal|"conf1"
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testReplaceVariables
parameter_list|()
throws|throws
name|Exception
block|{
name|_project
operator|.
name|setProperty
argument_list|(
literal|"ivy.dep.file"
argument_list|,
literal|"test/java/fr/jayasoft/ivy/ant/ivy-with-variables.xml"
argument_list|)
expr_stmt|;
name|IvyResolve
name|res
init|=
operator|new
name|IvyResolve
argument_list|()
decl_stmt|;
name|res
operator|.
name|setProject
argument_list|(
name|_project
argument_list|)
expr_stmt|;
name|res
operator|.
name|execute
argument_list|()
expr_stmt|;
name|res
operator|.
name|getIvyInstance
argument_list|()
operator|.
name|setVariable
argument_list|(
literal|"myvar"
argument_list|,
literal|"myvalue"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|setPubrevision
argument_list|(
literal|"1.2"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|setDeliverpattern
argument_list|(
literal|"build/test/deliver/ivy-[revision].xml"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// should have done the ivy delivering
name|File
name|deliveredIvyFile
init|=
operator|new
name|File
argument_list|(
literal|"build/test/deliver/ivy-1.2.xml"
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|deliveredIvyFile
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|String
name|deliveredFileContent
init|=
name|FileUtil
operator|.
name|readEntirely
argument_list|(
operator|new
name|BufferedReader
argument_list|(
operator|new
name|FileReader
argument_list|(
name|deliveredIvyFile
argument_list|)
argument_list|)
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"variable not replaced: myvar can still be found in file"
argument_list|,
name|deliveredFileContent
operator|.
name|indexOf
argument_list|(
literal|"myvar"
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
literal|"variable not replaced: myvalue cannot be found in file"
argument_list|,
name|deliveredFileContent
operator|.
name|indexOf
argument_list|(
literal|"myvalue"
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testNoReplaceDynamicRev
parameter_list|()
throws|throws
name|Exception
block|{
name|_project
operator|.
name|setProperty
argument_list|(
literal|"ivy.dep.file"
argument_list|,
literal|"test/java/fr/jayasoft/ivy/ant/ivy-latest.xml"
argument_list|)
expr_stmt|;
name|IvyResolve
name|res
init|=
operator|new
name|IvyResolve
argument_list|()
decl_stmt|;
name|res
operator|.
name|setProject
argument_list|(
name|_project
argument_list|)
expr_stmt|;
name|res
operator|.
name|execute
argument_list|()
expr_stmt|;
name|_deliver
operator|.
name|setPubrevision
argument_list|(
literal|"1.2"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|setDeliverpattern
argument_list|(
literal|"build/test/deliver/ivy-[revision].xml"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|setReplacedynamicrev
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// should have done the ivy delivering
name|File
name|deliveredIvyFile
init|=
operator|new
name|File
argument_list|(
literal|"build/test/deliver/ivy-1.2.xml"
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|deliveredIvyFile
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|ModuleDescriptor
name|md
init|=
name|XmlModuleDescriptorParser
operator|.
name|getInstance
argument_list|()
operator|.
name|parseDescriptor
argument_list|(
operator|new
name|Ivy
argument_list|()
argument_list|,
name|deliveredIvyFile
operator|.
name|toURL
argument_list|()
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"jayasoft"
argument_list|,
literal|"resolve-latest"
argument_list|,
literal|"1.2"
argument_list|)
argument_list|,
name|md
operator|.
name|getModuleRevisionId
argument_list|()
argument_list|)
expr_stmt|;
name|DependencyDescriptor
index|[]
name|dds
init|=
name|md
operator|.
name|getDependencies
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|dds
operator|.
name|length
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"latest.integration"
argument_list|)
argument_list|,
name|dds
index|[
literal|0
index|]
operator|.
name|getDependencyRevisionId
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testDifferentRevisionsForSameModule
parameter_list|()
throws|throws
name|Exception
block|{
name|_project
operator|.
name|setProperty
argument_list|(
literal|"ivy.dep.file"
argument_list|,
literal|"test/java/fr/jayasoft/ivy/ant/ivy-different-revisions.xml"
argument_list|)
expr_stmt|;
name|IvyResolve
name|res
init|=
operator|new
name|IvyResolve
argument_list|()
decl_stmt|;
name|res
operator|.
name|setProject
argument_list|(
name|_project
argument_list|)
expr_stmt|;
name|res
operator|.
name|execute
argument_list|()
expr_stmt|;
name|_deliver
operator|.
name|setPubrevision
argument_list|(
literal|"1.2"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|setDeliverpattern
argument_list|(
literal|"build/test/deliver/ivy-[revision].xml"
argument_list|)
expr_stmt|;
name|_deliver
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// should have done the ivy delivering
name|File
name|deliveredIvyFile
init|=
operator|new
name|File
argument_list|(
literal|"build/test/deliver/ivy-1.2.xml"
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|deliveredIvyFile
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|ModuleDescriptor
name|md
init|=
name|XmlModuleDescriptorParser
operator|.
name|getInstance
argument_list|()
operator|.
name|parseDescriptor
argument_list|(
operator|new
name|Ivy
argument_list|()
argument_list|,
name|deliveredIvyFile
operator|.
name|toURL
argument_list|()
argument_list|,
literal|true
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"jayasoft"
argument_list|,
literal|"different-revs"
argument_list|,
literal|"1.2"
argument_list|)
argument_list|,
name|md
operator|.
name|getModuleRevisionId
argument_list|()
argument_list|)
expr_stmt|;
name|DependencyDescriptor
index|[]
name|dds
init|=
name|md
operator|.
name|getDependencies
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|3
argument_list|,
name|dds
operator|.
name|length
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|)
argument_list|,
name|dds
index|[
literal|0
index|]
operator|.
name|getDependencyRevisionId
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.1"
argument_list|,
literal|"1.0"
argument_list|)
argument_list|,
name|dds
index|[
literal|1
index|]
operator|.
name|getDependencyRevisionId
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"1.1"
argument_list|)
argument_list|,
name|dds
index|[
literal|2
index|]
operator|.
name|getDependencyRevisionId
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

