begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|tools
operator|.
name|analyser
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|id
operator|.
name|ModuleRevisionId
import|;
end_import

begin_class
specifier|public
class|class
name|JarModule
block|{
specifier|private
name|ModuleRevisionId
name|_mrid
decl_stmt|;
specifier|private
name|File
name|_jar
decl_stmt|;
specifier|public
name|JarModule
parameter_list|(
name|ModuleRevisionId
name|mrid
parameter_list|,
name|File
name|jar
parameter_list|)
block|{
name|_mrid
operator|=
name|mrid
expr_stmt|;
name|_jar
operator|=
name|jar
expr_stmt|;
block|}
specifier|public
name|File
name|getJar
parameter_list|()
block|{
return|return
name|_jar
return|;
block|}
specifier|public
name|ModuleRevisionId
name|getMrid
parameter_list|()
block|{
return|return
name|_mrid
return|;
block|}
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
name|_jar
operator|+
literal|" "
operator|+
name|_mrid
return|;
block|}
block|}
end_class

end_unit

