begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|osgi
operator|.
name|updatesite
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|text
operator|.
name|ParseException
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|osgi
operator|.
name|repo
operator|.
name|RepoDescriptor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|xml
operator|.
name|sax
operator|.
name|SAXException
import|;
end_import

begin_class
specifier|public
class|class
name|UpdateSiteLoaderTest
extends|extends
name|TestCase
block|{
specifier|public
name|void
name|testIvyDE
parameter_list|()
throws|throws
name|IOException
throws|,
name|ParseException
throws|,
name|SAXException
block|{
name|UpdateSiteLoader
name|loader
init|=
operator|new
name|UpdateSiteLoader
argument_list|()
decl_stmt|;
name|RepoDescriptor
name|site
init|=
name|loader
operator|.
name|load
argument_list|(
literal|"http://www.apache.org/dist/ant/ivyde/updatesite/"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|13
argument_list|,
name|site
operator|.
name|getModules
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testEclipse
parameter_list|()
throws|throws
name|IOException
throws|,
name|ParseException
throws|,
name|SAXException
block|{
name|UpdateSiteLoader
name|loader
init|=
operator|new
name|UpdateSiteLoader
argument_list|()
decl_stmt|;
name|RepoDescriptor
name|site
init|=
name|loader
operator|.
name|load
argument_list|(
literal|"http://download.eclipse.org/releases/helios/"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|13
argument_list|,
name|site
operator|.
name|getModules
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

