begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|descriptor
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Arrays
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|id
operator|.
name|ModuleRevisionId
import|;
end_import

begin_class
specifier|public
class|class
name|DefaultExtendsDescriptor
implements|implements
name|ExtendsDescriptor
block|{
specifier|private
name|ModuleDescriptor
name|parent
decl_stmt|;
specifier|private
name|String
name|location
decl_stmt|;
specifier|private
name|List
name|extendsTypes
decl_stmt|;
specifier|private
name|boolean
name|local
decl_stmt|;
specifier|public
name|DefaultExtendsDescriptor
parameter_list|(
name|ModuleDescriptor
name|parent
parameter_list|,
name|String
name|location
parameter_list|,
name|String
index|[]
name|types
parameter_list|)
block|{
name|this
argument_list|(
name|parent
argument_list|,
name|location
argument_list|,
name|types
argument_list|,
literal|false
argument_list|)
expr_stmt|;
block|}
specifier|public
name|DefaultExtendsDescriptor
parameter_list|(
name|ModuleDescriptor
name|parent
parameter_list|,
name|String
name|location
parameter_list|,
name|String
index|[]
name|types
parameter_list|,
name|boolean
name|local
parameter_list|)
block|{
name|this
operator|.
name|parent
operator|=
name|parent
expr_stmt|;
name|this
operator|.
name|location
operator|=
name|location
expr_stmt|;
name|this
operator|.
name|local
operator|=
name|local
expr_stmt|;
name|this
operator|.
name|extendsTypes
operator|=
operator|new
name|ArrayList
argument_list|(
name|types
operator|.
name|length
argument_list|)
expr_stmt|;
name|extendsTypes
operator|.
name|addAll
argument_list|(
name|Arrays
operator|.
name|asList
argument_list|(
name|types
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|ModuleRevisionId
name|getParentRevisionId
parameter_list|()
block|{
return|return
name|parent
operator|.
name|getModuleRevisionId
argument_list|()
return|;
block|}
specifier|public
name|ModuleRevisionId
name|getResolvedParentRevisionId
parameter_list|()
block|{
return|return
name|parent
operator|.
name|getResolvedModuleRevisionId
argument_list|()
return|;
block|}
specifier|public
name|ModuleDescriptor
name|getParentMd
parameter_list|()
block|{
return|return
name|parent
return|;
block|}
specifier|public
name|String
name|getLocation
parameter_list|()
block|{
return|return
name|location
return|;
block|}
specifier|public
name|String
index|[]
name|getExtendsTypes
parameter_list|()
block|{
return|return
operator|(
name|String
index|[]
operator|)
name|extendsTypes
operator|.
name|toArray
argument_list|(
operator|new
name|String
index|[
name|extendsTypes
operator|.
name|size
argument_list|()
index|]
argument_list|)
return|;
block|}
specifier|public
name|boolean
name|isAllInherited
parameter_list|()
block|{
return|return
name|extendsTypes
operator|.
name|contains
argument_list|(
literal|"all"
argument_list|)
return|;
block|}
specifier|public
name|boolean
name|isInfoInherited
parameter_list|()
block|{
return|return
name|isAllInherited
argument_list|()
operator|||
name|extendsTypes
operator|.
name|contains
argument_list|(
literal|"info"
argument_list|)
return|;
block|}
specifier|public
name|boolean
name|isDescriptionInherited
parameter_list|()
block|{
return|return
name|isAllInherited
argument_list|()
operator|||
name|extendsTypes
operator|.
name|contains
argument_list|(
literal|"description"
argument_list|)
return|;
block|}
specifier|public
name|boolean
name|areConfigurationsInherited
parameter_list|()
block|{
return|return
name|isAllInherited
argument_list|()
operator|||
name|extendsTypes
operator|.
name|contains
argument_list|(
literal|"configurations"
argument_list|)
return|;
block|}
specifier|public
name|boolean
name|areDependenciesInherited
parameter_list|()
block|{
return|return
name|isAllInherited
argument_list|()
operator|||
name|extendsTypes
operator|.
name|contains
argument_list|(
literal|"dependencies"
argument_list|)
return|;
block|}
specifier|public
name|boolean
name|isLocal
parameter_list|()
block|{
return|return
name|local
return|;
block|}
block|}
end_class

end_unit

