begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * This file is subject to the licence found in LICENCE.TXT in the root directory of the project.  * Copyright Jayasoft 2005 - All rights reserved  *   * #SNAPSHOT#  */
end_comment

begin_package
package|package
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|repository
package|;
end_package

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|util
operator|.
name|CopyProgressEvent
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|util
operator|.
name|CopyProgressListener
import|;
end_import

begin_class
specifier|public
class|class
name|RepositoryCopyProgressListener
implements|implements
name|CopyProgressListener
block|{
specifier|private
specifier|final
name|AbstractRepository
name|_repository
decl_stmt|;
specifier|public
name|RepositoryCopyProgressListener
parameter_list|(
name|AbstractRepository
name|repository
parameter_list|)
block|{
name|_repository
operator|=
name|repository
expr_stmt|;
block|}
specifier|private
name|Long
name|_totalLength
init|=
literal|null
decl_stmt|;
specifier|public
name|void
name|start
parameter_list|(
name|CopyProgressEvent
name|evt
parameter_list|)
block|{
if|if
condition|(
name|_totalLength
operator|!=
literal|null
condition|)
block|{
name|_repository
operator|.
name|fireTransferStarted
argument_list|(
name|_totalLength
operator|.
name|longValue
argument_list|()
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|_repository
operator|.
name|fireTransferStarted
argument_list|()
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|progress
parameter_list|(
name|CopyProgressEvent
name|evt
parameter_list|)
block|{
name|_repository
operator|.
name|fireTransferProgress
argument_list|(
name|evt
operator|.
name|getBuffer
argument_list|()
argument_list|,
name|evt
operator|.
name|getReadBytes
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|end
parameter_list|(
name|CopyProgressEvent
name|evt
parameter_list|)
block|{
name|_repository
operator|.
name|fireTransferCompleted
argument_list|(
name|evt
operator|.
name|getBuffer
argument_list|()
argument_list|,
name|evt
operator|.
name|getReadBytes
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|Long
name|getTotalLength
parameter_list|()
block|{
return|return
name|_totalLength
return|;
block|}
specifier|public
name|void
name|setTotalLength
parameter_list|(
name|Long
name|totalLength
parameter_list|)
block|{
name|_totalLength
operator|=
name|totalLength
expr_stmt|;
block|}
block|}
end_class

end_unit

