begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * This file is subject to the licence found in LICENCE.TXT in the root directory of the project.  * Copyright Jayasoft 2005 - All rights reserved  *   * #SNAPSHOT#  */
end_comment

begin_package
package|package
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|matcher
package|;
end_package

begin_class
specifier|public
class|class
name|NoMatcher
implements|implements
name|Matcher
block|{
specifier|private
specifier|final
specifier|static
name|Matcher
name|INSTANCE
init|=
operator|new
name|NoMatcher
argument_list|()
decl_stmt|;
specifier|public
specifier|static
name|Matcher
name|getInstance
parameter_list|()
block|{
return|return
name|INSTANCE
return|;
block|}
specifier|private
name|NoMatcher
parameter_list|()
block|{
block|}
specifier|public
name|boolean
name|matches
parameter_list|(
name|String
name|str
parameter_list|)
block|{
return|return
literal|false
return|;
block|}
specifier|public
name|boolean
name|isExact
parameter_list|()
block|{
return|return
literal|true
return|;
block|}
block|}
end_class

end_unit

