begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * This file is subject to the licence found in LICENCE.TXT in the root directory of the project.  * Copyright Jayasoft 2005 - All rights reserved  *   * #SNAPSHOT#  */
end_comment

begin_package
package|package
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|matcher
package|;
end_package

begin_interface
specifier|public
interface|interface
name|PatternMatcher
block|{
specifier|public
specifier|static
specifier|final
name|String
name|EXACT
init|=
literal|"exact"
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|REGEXP
init|=
literal|"regexp"
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|GLOB
init|=
literal|"glob"
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|EXACT_OR_REGEXP
init|=
literal|"exactOrRegexp"
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|ANY_EXPRESSION
init|=
literal|"*"
decl_stmt|;
specifier|public
name|Matcher
name|getMatcher
parameter_list|(
name|String
name|exp
parameter_list|)
function_decl|;
specifier|public
name|String
name|getName
parameter_list|()
function_decl|;
block|}
end_interface

end_unit

