begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|util
package|;
end_package

begin_comment
comment|/**  *   * @author Christian Riege  * @author Xavier Hanin  */
end_comment

begin_class
specifier|public
class|class
name|Credentials
block|{
specifier|private
name|String
name|_realm
decl_stmt|;
specifier|private
name|String
name|_host
decl_stmt|;
specifier|private
name|String
name|_userName
decl_stmt|;
specifier|private
name|String
name|_passwd
decl_stmt|;
specifier|public
name|Credentials
parameter_list|(
name|String
name|realm
parameter_list|,
name|String
name|host
parameter_list|,
name|String
name|userName
parameter_list|,
name|String
name|passwd
parameter_list|)
block|{
name|_realm
operator|=
name|realm
expr_stmt|;
name|_host
operator|=
name|host
expr_stmt|;
name|_userName
operator|=
name|userName
expr_stmt|;
name|_passwd
operator|=
name|passwd
expr_stmt|;
block|}
specifier|public
name|String
name|getHost
parameter_list|()
block|{
return|return
name|_host
return|;
block|}
specifier|public
name|String
name|getPasswd
parameter_list|()
block|{
return|return
name|_passwd
return|;
block|}
specifier|public
name|String
name|getRealm
parameter_list|()
block|{
return|return
name|_realm
return|;
block|}
specifier|public
name|String
name|getUserName
parameter_list|()
block|{
return|return
name|_userName
return|;
block|}
specifier|public
specifier|static
name|String
name|buildKey
parameter_list|(
name|String
name|realm
parameter_list|,
name|String
name|host
parameter_list|)
block|{
if|if
condition|(
name|realm
operator|==
literal|null
operator|||
literal|""
operator|.
name|equals
argument_list|(
name|realm
operator|.
name|trim
argument_list|()
argument_list|)
condition|)
block|{
return|return
name|host
return|;
block|}
else|else
block|{
return|return
name|realm
operator|+
literal|"@"
operator|+
name|host
return|;
block|}
block|}
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
name|getKey
argument_list|()
operator|+
literal|" "
operator|+
name|getUserName
argument_list|()
operator|+
literal|"/"
operator|+
name|getPasswd
argument_list|()
return|;
block|}
specifier|public
name|boolean
name|equals
parameter_list|(
name|Object
name|o
parameter_list|)
block|{
if|if
condition|(
name|o
operator|==
literal|null
condition|)
block|{
return|return
literal|false
return|;
block|}
if|if
condition|(
name|o
operator|instanceof
name|Credentials
condition|)
block|{
name|Credentials
name|c
init|=
operator|(
name|Credentials
operator|)
name|o
decl_stmt|;
return|return
name|getKey
argument_list|()
operator|.
name|equals
argument_list|(
name|c
operator|.
name|getKey
argument_list|()
argument_list|)
return|;
block|}
return|return
literal|false
return|;
block|}
specifier|public
name|int
name|hashCode
parameter_list|()
block|{
return|return
name|getKey
argument_list|()
operator|.
name|hashCode
argument_list|()
return|;
block|}
specifier|public
name|String
name|getKey
parameter_list|()
block|{
return|return
name|buildKey
argument_list|(
name|_realm
argument_list|,
name|_host
argument_list|)
return|;
block|}
block|}
end_class

end_unit

