begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|plugins
operator|.
name|conflict
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|text
operator|.
name|ParseException
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|Ivy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|TestHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|cache
operator|.
name|CacheManager
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|report
operator|.
name|ConfigurationResolveReport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|report
operator|.
name|ResolveReport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|resolve
operator|.
name|ResolveOptions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|util
operator|.
name|DefaultMessageLogger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|util
operator|.
name|FileUtil
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|util
operator|.
name|Message
import|;
end_import

begin_class
specifier|public
class|class
name|LatestCompatibleConflictManagerTest
extends|extends
name|TestCase
block|{
specifier|private
name|Ivy
name|ivy
decl_stmt|;
specifier|private
name|File
name|cache
decl_stmt|;
specifier|protected
name|void
name|setUp
parameter_list|()
throws|throws
name|Exception
block|{
name|Message
operator|.
name|setDefaultLogger
argument_list|(
operator|new
name|DefaultMessageLogger
argument_list|(
name|Message
operator|.
name|MSG_DEBUG
argument_list|)
argument_list|)
expr_stmt|;
name|ivy
operator|=
operator|new
name|Ivy
argument_list|()
expr_stmt|;
name|ivy
operator|.
name|configure
argument_list|(
name|LatestCompatibleConflictManagerTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivysettings-latest-compatible.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|cache
operator|=
operator|new
name|File
argument_list|(
literal|"build/cache"
argument_list|)
expr_stmt|;
name|cache
operator|.
name|mkdirs
argument_list|()
expr_stmt|;
block|}
specifier|protected
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{
name|FileUtil
operator|.
name|forceDelete
argument_list|(
name|cache
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testInitFromSettings
parameter_list|()
throws|throws
name|Exception
block|{
name|ConflictManager
name|cm
init|=
name|ivy
operator|.
name|getSettings
argument_list|()
operator|.
name|getDefaultConflictManager
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|cm
operator|instanceof
name|LatestCompatibleConflictManager
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCompatibilityResolve1
parameter_list|()
throws|throws
name|Exception
block|{
comment|/* Test data:             #A;1-> { #B;1.4 #C;[2.0,2.5] }             #B;1.4->#D;1.5             #C;2.5->#D;[1.0,1.6]          */
name|resolveAndAssert
argument_list|(
literal|"ivy-latest-compatible-1.xml"
argument_list|,
literal|"#B;1.4, #C;2.5, #D;1.5"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCompatibilityResolve2
parameter_list|()
throws|throws
name|Exception
block|{
comment|/* Test data:             #A;2-> { #B;[1.0,1.5] #C;[2.0,2.5] }             #B;1.4->#D;1.5             #B;1.5->#D;2.0             #C;2.5->#D;[1.0,1.6]          */
name|resolveAndAssert
argument_list|(
literal|"ivy-latest-compatible-2.xml"
argument_list|,
literal|"#B;1.4, #C;2.5, #D;1.5"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCompatibilityResolve3
parameter_list|()
throws|throws
name|Exception
block|{
comment|/* Test data:             #A;3-> { #B;[2.0,2.5] #C;[3.0,3.5] }             #B;2.3-> { #D;1.5 #E;1.0 }             #B;2.4-> { #D;1.5 #E;2.0 }             #B;2.5-> { #D;2.0 }             #C;3.4-> { #D;[1.0,1.6] #E;1.0 }              #C;3.5-> { #D;[1.0,1.6] #E;1.9 }           */
name|resolveAndAssert
argument_list|(
literal|"ivy-latest-compatible-3.xml"
argument_list|,
literal|"#B;2.3, #C;3.4, #D;1.5, #E;1.0"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCompatibilityResolve4
parameter_list|()
throws|throws
name|Exception
block|{
comment|/* Test data:             #A;4-> { #B;[1.0,1.5] #C;[2.0,2.5] #F;[1.0,1.1] }             #B;1.4->#D;1.5             #B;1.5->#D;2.0             #C;2.5->#D;[1.0,1.6]             #F;1.0->#D;1.5             #F;1.1->#D;1.6          */
name|resolveAndAssert
argument_list|(
literal|"ivy-latest-compatible-4.xml"
argument_list|,
literal|"#B;1.4, #C;2.5, #D;1.5, #F;1.0"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCompatibilityResolve5
parameter_list|()
throws|throws
name|Exception
block|{
comment|/* Test data:             #A;5->{ #B;[1.0,1.5] #C;2.6 }             #B;1.3->{ }             #B;1.4->#D;1.5             #B;1.5->#D;2.0             #C;2.6->#D;1.6          */
name|resolveAndAssert
argument_list|(
literal|"ivy-latest-compatible-5.xml"
argument_list|,
literal|"#B;1.3, #C;2.6, #D;1.6"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCompatibilityResolve6
parameter_list|()
throws|throws
name|Exception
block|{
comment|/* Test data:             #A;6->{ #B;[3.0,3.5] #C;4.6 }             #B;3.4->#D;2.5             #B;3.5->#D;3.0             #C;4.6->#D;2.5             #D;3.0->#B;3.5 (circular dependency)             #D;2.5->#B;3.4 (circular dependency)          */
name|resolveAndAssert
argument_list|(
literal|"ivy-latest-compatible-6.xml"
argument_list|,
literal|"#B;3.4, #C;4.6, #D;2.5"
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testConflict
parameter_list|()
throws|throws
name|Exception
block|{
comment|/* Test data:             #A;conflict-> { #B;[1.5,1.6] #C;2.5 }             #B;1.5->#D;2.0             #B;1.6->#D;2.0             #C;2.5->#D;[1.0,1.6]          */
try|try
block|{
name|ivy
operator|.
name|resolve
argument_list|(
name|LatestCompatibleConflictManagerTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivy-latest-compatible-conflict.xml"
argument_list|)
argument_list|,
name|getResolveOptions
argument_list|()
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"Resolve should have failed with a conflict"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|StrictConflictException
name|e
parameter_list|)
block|{
comment|// this is expected
block|}
block|}
specifier|private
name|void
name|resolveAndAssert
parameter_list|(
name|String
name|ivyFile
parameter_list|,
name|String
name|expectedModuleSet
parameter_list|)
throws|throws
name|ParseException
throws|,
name|IOException
block|{
name|ResolveReport
name|report
init|=
name|ivy
operator|.
name|resolve
argument_list|(
name|LatestCompatibleConflictManagerTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
name|ivyFile
argument_list|)
argument_list|,
name|getResolveOptions
argument_list|()
argument_list|)
decl_stmt|;
name|assertFalse
argument_list|(
name|report
operator|.
name|hasError
argument_list|()
argument_list|)
expr_stmt|;
name|ConfigurationResolveReport
name|defaultReport
init|=
name|report
operator|.
name|getConfigurationReport
argument_list|(
literal|"default"
argument_list|)
decl_stmt|;
name|TestHelper
operator|.
name|assertModuleRevisionIds
argument_list|(
name|expectedModuleSet
argument_list|,
name|defaultReport
operator|.
name|getModuleRevisionIds
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|private
name|ResolveOptions
name|getResolveOptions
parameter_list|()
block|{
return|return
operator|new
name|ResolveOptions
argument_list|()
operator|.
name|setCache
argument_list|(
name|CacheManager
operator|.
name|getInstance
argument_list|(
name|ivy
operator|.
name|getSettings
argument_list|()
argument_list|)
argument_list|)
operator|.
name|setValidate
argument_list|(
literal|false
argument_list|)
return|;
block|}
block|}
end_class

end_unit

