begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|plugins
operator|.
name|conflict
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|Ivy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|resolve
operator|.
name|ResolveOptions
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|util
operator|.
name|FileUtil
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_class
specifier|public
class|class
name|StrictConflictManagerTest
extends|extends
name|TestCase
block|{
specifier|private
name|Ivy
name|ivy
decl_stmt|;
specifier|private
name|File
name|cache
decl_stmt|;
specifier|protected
name|void
name|setUp
parameter_list|()
throws|throws
name|Exception
block|{
name|ivy
operator|=
operator|new
name|Ivy
argument_list|()
expr_stmt|;
name|ivy
operator|.
name|configure
argument_list|(
name|StrictConflictManagerTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivysettings-strict-test.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|cache
operator|=
operator|new
name|File
argument_list|(
literal|"build/cache"
argument_list|)
expr_stmt|;
name|cache
operator|.
name|mkdirs
argument_list|()
expr_stmt|;
block|}
specifier|protected
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{
name|FileUtil
operator|.
name|forceDelete
argument_list|(
name|cache
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testInitFromConf
parameter_list|()
throws|throws
name|Exception
block|{
name|ConflictManager
name|cm
init|=
name|ivy
operator|.
name|getSettings
argument_list|()
operator|.
name|getDefaultConflictManager
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|cm
operator|instanceof
name|StrictConflictManager
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testNoConflictResolve
parameter_list|()
throws|throws
name|Exception
block|{
name|ivy
operator|.
name|resolve
argument_list|(
name|StrictConflictManagerTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivy-noconflict.xml"
argument_list|)
argument_list|,
name|getResolveOptions
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testNoConflictWithDynamicRevisionResolve
parameter_list|()
throws|throws
name|Exception
block|{
name|ivy
operator|.
name|resolve
argument_list|(
name|StrictConflictManagerTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivy-noconflict-dynamic.xml"
argument_list|)
argument_list|,
name|getResolveOptions
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testConflictResolve
parameter_list|()
throws|throws
name|Exception
block|{
try|try
block|{
name|ivy
operator|.
name|resolve
argument_list|(
name|StrictConflictManagerTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivy-conflict.xml"
argument_list|)
argument_list|,
name|getResolveOptions
argument_list|()
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"Resolve should have failed with a conflict"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|StrictConflictException
name|e
parameter_list|)
block|{
comment|// this is expected
block|}
block|}
specifier|public
name|void
name|testConflictWithDynamicRevisionResolve
parameter_list|()
throws|throws
name|Exception
block|{
try|try
block|{
name|ivy
operator|.
name|resolve
argument_list|(
name|StrictConflictManagerTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivy-conflict-dynamic.xml"
argument_list|)
argument_list|,
name|getResolveOptions
argument_list|()
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"Resolve should have failed with a conflict"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|StrictConflictException
name|e
parameter_list|)
block|{
comment|// this is expected
block|}
block|}
specifier|private
name|ResolveOptions
name|getResolveOptions
parameter_list|()
block|{
return|return
operator|new
name|ResolveOptions
argument_list|()
operator|.
name|setValidate
argument_list|(
literal|false
argument_list|)
return|;
block|}
block|}
end_class

end_unit

