begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|plugins
operator|.
name|circular
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|id
operator|.
name|ModuleRevisionId
import|;
end_import

begin_comment
comment|/**  * Unchecked exception thrown when a circular dependency exists between projects.  */
end_comment

begin_class
specifier|public
class|class
name|CircularDependencyException
extends|extends
name|RuntimeException
block|{
comment|/**      *      */
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
literal|670272039106237360L
decl_stmt|;
specifier|private
name|ModuleRevisionId
index|[]
name|mrids
decl_stmt|;
comment|/**      * @param mrids      *            module descriptors in order of circular dependency      */
specifier|public
name|CircularDependencyException
parameter_list|(
specifier|final
name|ModuleRevisionId
index|[]
name|mrids
parameter_list|)
block|{
name|super
argument_list|(
name|CircularDependencyHelper
operator|.
name|formatMessage
argument_list|(
name|mrids
argument_list|)
argument_list|)
expr_stmt|;
name|this
operator|.
name|mrids
operator|=
name|mrids
expr_stmt|;
block|}
specifier|public
name|CircularDependencyException
parameter_list|(
specifier|final
name|Collection
argument_list|<
name|ModuleRevisionId
argument_list|>
name|mrids
parameter_list|)
block|{
name|this
argument_list|(
name|mrids
operator|.
name|toArray
argument_list|(
operator|new
name|ModuleRevisionId
index|[
name|mrids
operator|.
name|size
argument_list|()
index|]
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|ModuleRevisionId
index|[]
name|getPath
parameter_list|()
block|{
return|return
name|this
operator|.
name|mrids
return|;
block|}
block|}
end_class

end_unit

