begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|plugins
operator|.
name|namespace
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Date
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|descriptor
operator|.
name|Artifact
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|descriptor
operator|.
name|DefaultArtifact
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|id
operator|.
name|ArtifactRevisionId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|id
operator|.
name|ModuleRevisionId
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_class
specifier|public
class|class
name|NameSpaceHelperTest
extends|extends
name|TestCase
block|{
specifier|public
name|void
name|testTransformArtifactWithExtraAttributes
parameter_list|()
throws|throws
name|Exception
block|{
name|Artifact
name|artifact
init|=
operator|new
name|DefaultArtifact
argument_list|(
name|ArtifactRevisionId
operator|.
name|newInstance
argument_list|(
name|ModuleRevisionId
operator|.
name|parse
argument_list|(
literal|"org.apache#test;1.0"
argument_list|)
argument_list|,
literal|"test"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|,
name|Collections
operator|.
name|singletonMap
argument_list|(
literal|"m:qualifier"
argument_list|,
literal|"sources"
argument_list|)
argument_list|)
argument_list|,
operator|new
name|Date
argument_list|()
argument_list|,
literal|null
argument_list|,
literal|false
argument_list|)
decl_stmt|;
name|MRIDTransformationRule
name|r
init|=
operator|new
name|MRIDTransformationRule
argument_list|()
decl_stmt|;
name|r
operator|.
name|addSrc
argument_list|(
operator|new
name|MRIDRule
argument_list|(
literal|"org.apache"
argument_list|,
literal|"test"
argument_list|,
literal|null
argument_list|)
argument_list|)
expr_stmt|;
name|r
operator|.
name|addDest
argument_list|(
operator|new
name|MRIDRule
argument_list|(
literal|"apache"
argument_list|,
literal|"test"
argument_list|,
literal|null
argument_list|)
argument_list|)
expr_stmt|;
name|Artifact
name|transformed
init|=
name|NameSpaceHelper
operator|.
name|transform
argument_list|(
name|artifact
argument_list|,
name|r
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"apache#test;1.0"
argument_list|,
name|transformed
operator|.
name|getModuleRevisionId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|Collections
operator|.
name|singletonMap
argument_list|(
literal|"m:qualifier"
argument_list|,
literal|"sources"
argument_list|)
argument_list|,
name|transformed
operator|.
name|getQualifiedExtraAttributes
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

