begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * This file is subject to the license found in LICENCE.TXT in the root directory of the project.  *   * #SNAPSHOT#  */
end_comment

begin_package
package|package
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|xml
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URL
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|DependencyResolver
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|Ivy
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|LatestStrategy
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|ModuleId
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|latest
operator|.
name|LatestRevisionStrategy
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|latest
operator|.
name|LatestTimeStrategy
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|parser
operator|.
name|ModuleDescriptorParserRegistry
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|report
operator|.
name|ReportOutputter
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|report
operator|.
name|ResolveReport
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|resolver
operator|.
name|ChainResolver
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|resolver
operator|.
name|FileSystemResolver
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|resolver
operator|.
name|IvyRepResolver
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|resolver
operator|.
name|MockResolver
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|url
operator|.
name|URLHandler
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|url
operator|.
name|URLHandlerDispatcher
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|url
operator|.
name|URLHandlerRegistry
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|version
operator|.
name|ChainVersionMatcher
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|version
operator|.
name|MockVersionMatcher
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|version
operator|.
name|VersionMatcher
import|;
end_import

begin_comment
comment|/**  * TODO write javadoc  */
end_comment

begin_class
specifier|public
class|class
name|XmlIvyConfigurationParserTest
extends|extends
name|TestCase
block|{
specifier|public
name|void
name|test
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-test.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|File
name|defaultCache
init|=
name|ivy
operator|.
name|getDefaultCache
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|defaultCache
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"mycache"
argument_list|,
name|defaultCache
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|ivy
operator|.
name|isCheckUpToDate
argument_list|()
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|ivy
operator|.
name|doValidate
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"[module]/ivys/ivy-[revision].xml"
argument_list|,
name|ivy
operator|.
name|getCacheIvyPattern
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"[module]/[type]s/[artifact]-[revision].[ext]"
argument_list|,
name|ivy
operator|.
name|getCacheArtifactPattern
argument_list|()
argument_list|)
expr_stmt|;
name|LatestStrategy
name|latest
init|=
name|ivy
operator|.
name|getLatestStrategy
argument_list|(
literal|"mylatest-revision"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|latest
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|latest
operator|instanceof
name|LatestRevisionStrategy
argument_list|)
expr_stmt|;
name|LatestRevisionStrategy
name|l
init|=
operator|(
name|LatestRevisionStrategy
operator|)
name|latest
decl_stmt|;
name|assertEquals
argument_list|(
operator|new
name|Integer
argument_list|(
operator|-
literal|2
argument_list|)
argument_list|,
name|l
operator|.
name|getSpecialMeanings
argument_list|()
operator|.
name|get
argument_list|(
literal|"pre"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
operator|new
name|Integer
argument_list|(
literal|4
argument_list|)
argument_list|,
name|l
operator|.
name|getSpecialMeanings
argument_list|()
operator|.
name|get
argument_list|(
literal|"qa"
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|defaultResolver
init|=
name|ivy
operator|.
name|getDefaultResolver
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|defaultResolver
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"libraries"
argument_list|,
name|defaultResolver
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|defaultResolver
operator|instanceof
name|FileSystemResolver
argument_list|)
expr_stmt|;
name|FileSystemResolver
name|fsres
init|=
operator|(
name|FileSystemResolver
operator|)
name|defaultResolver
decl_stmt|;
name|List
name|ivyPatterns
init|=
name|fsres
operator|.
name|getIvyPatterns
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|ivyPatterns
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|ivyPatterns
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"lib/[organisation]/[module]/ivys/ivy-[revision].xml"
argument_list|,
name|ivyPatterns
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|LatestStrategy
name|strategy
init|=
name|fsres
operator|.
name|getLatestStrategy
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|strategy
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|strategy
operator|instanceof
name|LatestRevisionStrategy
argument_list|)
expr_stmt|;
name|DependencyResolver
name|internal
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"internal"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|internal
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|internal
operator|instanceof
name|ChainResolver
argument_list|)
expr_stmt|;
name|ChainResolver
name|chain
init|=
operator|(
name|ChainResolver
operator|)
name|internal
decl_stmt|;
name|List
name|subresolvers
init|=
name|chain
operator|.
name|getResolvers
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|subresolvers
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|subresolvers
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|FileSystemResolver
name|fsInt1
init|=
operator|(
name|FileSystemResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"int1"
argument_list|,
name|fsInt1
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|fsInt1
operator|.
name|getIvyPatterns
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"sharedrep/[organisation]/[module]/ivys/ivy-[revision].xml"
argument_list|,
name|fsInt1
operator|.
name|getIvyPatterns
argument_list|()
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"int2"
argument_list|,
operator|(
operator|(
name|DependencyResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|1
argument_list|)
operator|)
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|strategy
operator|=
name|fsInt1
operator|.
name|getLatestStrategy
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|strategy
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|strategy
operator|instanceof
name|LatestTimeStrategy
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"libraries"
argument_list|,
name|ivy
operator|.
name|getResolver
argument_list|(
operator|new
name|ModuleId
argument_list|(
literal|"unknown"
argument_list|,
literal|"lib"
argument_list|)
argument_list|)
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"internal"
argument_list|,
name|ivy
operator|.
name|getResolver
argument_list|(
operator|new
name|ModuleId
argument_list|(
literal|"jayasoft"
argument_list|,
literal|"swtbinding"
argument_list|)
argument_list|)
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"int1"
argument_list|,
name|ivy
operator|.
name|getResolver
argument_list|(
operator|new
name|ModuleId
argument_list|(
literal|"jayasoft"
argument_list|,
literal|"ivy"
argument_list|)
argument_list|)
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"int1"
argument_list|,
name|ivy
operator|.
name|getResolver
argument_list|(
operator|new
name|ModuleId
argument_list|(
literal|"jayasoft"
argument_list|,
literal|"ivycruise"
argument_list|)
argument_list|)
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testTypedef
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-typedef.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|mock
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"mock3"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|mock
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|mock
operator|instanceof
name|MockResolver
argument_list|)
expr_stmt|;
name|DependencyResolver
name|internal
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"internal"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|internal
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|internal
operator|instanceof
name|ChainResolver
argument_list|)
expr_stmt|;
name|ChainResolver
name|chain
init|=
operator|(
name|ChainResolver
operator|)
name|internal
decl_stmt|;
name|List
name|subresolvers
init|=
name|chain
operator|.
name|getResolvers
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|subresolvers
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|subresolvers
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"mock1"
argument_list|,
operator|(
operator|(
name|DependencyResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|)
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"mock2"
argument_list|,
operator|(
operator|(
name|DependencyResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|1
argument_list|)
operator|)
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|subresolvers
operator|.
name|get
argument_list|(
literal|0
argument_list|)
operator|instanceof
name|MockResolver
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|subresolvers
operator|.
name|get
argument_list|(
literal|1
argument_list|)
operator|instanceof
name|MockResolver
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testVersionMatchers1
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-vmatcher1.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|VersionMatcher
name|mock
init|=
name|ivy
operator|.
name|getVersionMatcher
argument_list|(
literal|"vmock"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|mock
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|mock
operator|instanceof
name|MockVersionMatcher
argument_list|)
expr_stmt|;
name|VersionMatcher
name|v
init|=
name|ivy
operator|.
name|getVersionMatcher
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|v
operator|instanceof
name|ChainVersionMatcher
argument_list|)
expr_stmt|;
name|ChainVersionMatcher
name|chain
init|=
operator|(
name|ChainVersionMatcher
operator|)
name|v
decl_stmt|;
name|assertEquals
argument_list|(
literal|3
argument_list|,
name|chain
operator|.
name|getMatchers
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|chain
operator|.
name|getMatchers
argument_list|()
operator|.
name|contains
argument_list|(
name|mock
argument_list|)
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|chain
operator|.
name|getMatchers
argument_list|()
operator|.
name|contains
argument_list|(
name|ivy
operator|.
name|getVersionMatcher
argument_list|(
literal|"exact"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|chain
operator|.
name|getMatchers
argument_list|()
operator|.
name|contains
argument_list|(
name|ivy
operator|.
name|getVersionMatcher
argument_list|(
literal|"latest"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testVersionMatchers2
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-vmatcher2.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|VersionMatcher
name|mock
init|=
name|ivy
operator|.
name|getVersionMatcher
argument_list|(
literal|"vmock"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|mock
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|mock
operator|instanceof
name|MockVersionMatcher
argument_list|)
expr_stmt|;
name|VersionMatcher
name|v
init|=
name|ivy
operator|.
name|getVersionMatcher
argument_list|()
decl_stmt|;
name|assertTrue
argument_list|(
name|v
operator|instanceof
name|ChainVersionMatcher
argument_list|)
expr_stmt|;
name|ChainVersionMatcher
name|chain
init|=
operator|(
name|ChainVersionMatcher
operator|)
name|v
decl_stmt|;
name|assertEquals
argument_list|(
literal|5
argument_list|,
name|chain
operator|.
name|getMatchers
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|chain
operator|.
name|getMatchers
argument_list|()
operator|.
name|contains
argument_list|(
name|mock
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testRef
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-ref.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|internal
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"internal"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|internal
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|internal
operator|instanceof
name|ChainResolver
argument_list|)
expr_stmt|;
name|ChainResolver
name|chain
init|=
operator|(
name|ChainResolver
operator|)
name|internal
decl_stmt|;
name|List
name|subresolvers
init|=
name|chain
operator|.
name|getResolvers
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|subresolvers
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|subresolvers
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|FileSystemResolver
name|fsInt1
init|=
operator|(
name|FileSystemResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"fs"
argument_list|,
name|fsInt1
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|List
name|ivyPatterns
init|=
name|fsInt1
operator|.
name|getIvyPatterns
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|ivyPatterns
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|ivyPatterns
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"sharedrep/[organisation]/[module]/ivys/ivy-[revision].xml"
argument_list|,
name|ivyPatterns
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|external
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"external"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|external
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|external
operator|instanceof
name|ChainResolver
argument_list|)
expr_stmt|;
name|chain
operator|=
operator|(
name|ChainResolver
operator|)
name|external
expr_stmt|;
name|subresolvers
operator|=
name|chain
operator|.
name|getResolvers
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|subresolvers
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|subresolvers
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|FileSystemResolver
name|fsInt2
init|=
operator|(
name|FileSystemResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"fs"
argument_list|,
name|fsInt2
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|ivyPatterns
operator|=
name|fsInt2
operator|.
name|getIvyPatterns
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|ivyPatterns
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|ivyPatterns
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"sharedrep/[organisation]/[module]/ivys/ivy-[revision].xml"
argument_list|,
name|ivyPatterns
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testMacro
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-macro.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|def
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"default"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|def
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|def
operator|instanceof
name|ChainResolver
argument_list|)
expr_stmt|;
name|ChainResolver
name|chain
init|=
operator|(
name|ChainResolver
operator|)
name|def
decl_stmt|;
name|List
name|subresolvers
init|=
name|chain
operator|.
name|getResolvers
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|subresolvers
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|subresolvers
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|FileSystemResolver
name|fsInt1
init|=
operator|(
name|FileSystemResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"default-fs1"
argument_list|,
name|fsInt1
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|List
name|ivyPatterns
init|=
name|fsInt1
operator|.
name|getIvyPatterns
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|ivyPatterns
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|ivyPatterns
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"path/to/myrep/[organisation]/[module]/[type]s/[artifact]-[revision].[ext]"
argument_list|,
name|ivyPatterns
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|FileSystemResolver
name|fsInt2
init|=
operator|(
name|FileSystemResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|1
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"default-fs2"
argument_list|,
name|fsInt2
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|ivyPatterns
operator|=
name|fsInt2
operator|.
name|getIvyPatterns
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|ivyPatterns
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|ivyPatterns
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"path/to/secondrep/[organisation]/[module]/[type]s/ivy-[revision].xml"
argument_list|,
name|ivyPatterns
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|other
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"other"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|other
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|other
operator|instanceof
name|ChainResolver
argument_list|)
expr_stmt|;
name|chain
operator|=
operator|(
name|ChainResolver
operator|)
name|other
expr_stmt|;
name|subresolvers
operator|=
name|chain
operator|.
name|getResolvers
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|subresolvers
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|subresolvers
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|fsInt2
operator|=
operator|(
name|FileSystemResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|1
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"other-fs2"
argument_list|,
name|fsInt2
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|ivyPatterns
operator|=
name|fsInt2
operator|.
name|getIvyPatterns
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|ivyPatterns
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|ivyPatterns
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"path/to/secondrep/[module]/[type]s/ivy-[revision].xml"
argument_list|,
name|ivyPatterns
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testInclude
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-include.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|def
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"default"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|def
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|def
operator|instanceof
name|ChainResolver
argument_list|)
expr_stmt|;
name|ChainResolver
name|chain
init|=
operator|(
name|ChainResolver
operator|)
name|def
decl_stmt|;
name|List
name|subresolvers
init|=
name|chain
operator|.
name|getResolvers
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|subresolvers
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|subresolvers
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|FileSystemResolver
name|fsInt1
init|=
operator|(
name|FileSystemResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|0
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"default-fs1"
argument_list|,
name|fsInt1
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|List
name|ivyPatterns
init|=
name|fsInt1
operator|.
name|getIvyPatterns
argument_list|()
decl_stmt|;
name|assertNotNull
argument_list|(
name|ivyPatterns
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|ivyPatterns
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"path/to/myrep/[organisation]/[module]/[type]s/[artifact]-[revision].[ext]"
argument_list|,
name|ivyPatterns
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|inc
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"includeworks"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|inc
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|inc
operator|instanceof
name|ChainResolver
argument_list|)
expr_stmt|;
name|chain
operator|=
operator|(
name|ChainResolver
operator|)
name|inc
expr_stmt|;
name|subresolvers
operator|=
name|chain
operator|.
name|getResolvers
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|subresolvers
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|2
argument_list|,
name|subresolvers
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|fsInt1
operator|=
operator|(
name|FileSystemResolver
operator|)
name|subresolvers
operator|.
name|get
argument_list|(
literal|0
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"includeworks-fs1"
argument_list|,
name|fsInt1
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|ivyPatterns
operator|=
name|fsInt1
operator|.
name|getIvyPatterns
argument_list|()
expr_stmt|;
name|assertNotNull
argument_list|(
name|ivyPatterns
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|ivyPatterns
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"included/myrep/[organisation]/[module]/[type]s/[artifact]-[revision].[ext]"
argument_list|,
name|ivyPatterns
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testIncludeHttpUrl
parameter_list|()
throws|throws
name|Exception
block|{
name|configureURLHandler
argument_list|()
expr_stmt|;
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
operator|new
name|URL
argument_list|(
literal|"http://www.jayasoft.org/misc/ivy/test/ivyconf-include-http-url.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|DependencyResolver
name|resolver
init|=
name|ivy
operator|.
name|getResolver
argument_list|(
literal|"ivyrep"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|resolver
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|resolver
operator|instanceof
name|IvyRepResolver
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testParser
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-parser.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"fr.jayasoft.ivy.parser.ModuleDescriptorParserRegistryTest$MyParser"
argument_list|,
name|ModuleDescriptorParserRegistry
operator|.
name|getInstance
argument_list|()
operator|.
name|getParsers
argument_list|()
index|[
literal|0
index|]
operator|.
name|getClass
argument_list|()
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testOutputter
parameter_list|()
throws|throws
name|Exception
block|{
name|Ivy
name|ivy
init|=
operator|new
name|Ivy
argument_list|()
decl_stmt|;
name|XmlIvyConfigurationParser
name|parser
init|=
operator|new
name|XmlIvyConfigurationParser
argument_list|(
name|ivy
argument_list|)
decl_stmt|;
name|parser
operator|.
name|parse
argument_list|(
name|XmlIvyConfigurationParserTest
operator|.
name|class
operator|.
name|getResource
argument_list|(
literal|"ivyconf-outputter.xml"
argument_list|)
argument_list|)
expr_stmt|;
comment|//System.out.println(Arrays.asList(ivy.getReportOutputters()));
name|ReportOutputter
name|testOutputter
init|=
name|ivy
operator|.
name|getReportOutputter
argument_list|(
literal|"test"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|testOutputter
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|testOutputter
operator|instanceof
name|MyOutputter
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|configureURLHandler
parameter_list|()
block|{
name|URLHandlerDispatcher
name|dispatcher
init|=
operator|new
name|URLHandlerDispatcher
argument_list|()
decl_stmt|;
name|URLHandler
name|httpHandler
init|=
name|URLHandlerRegistry
operator|.
name|getHttp
argument_list|(
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|dispatcher
operator|.
name|setDownloader
argument_list|(
literal|"http"
argument_list|,
name|httpHandler
argument_list|)
expr_stmt|;
name|dispatcher
operator|.
name|setDownloader
argument_list|(
literal|"https"
argument_list|,
name|httpHandler
argument_list|)
expr_stmt|;
name|URLHandlerRegistry
operator|.
name|setDefault
argument_list|(
name|dispatcher
argument_list|)
expr_stmt|;
block|}
specifier|public
specifier|static
class|class
name|MyOutputter
implements|implements
name|ReportOutputter
block|{
specifier|public
name|void
name|output
parameter_list|(
name|ResolveReport
name|report
parameter_list|,
name|File
name|destDir
parameter_list|)
block|{
block|}
specifier|public
name|String
name|getName
parameter_list|()
block|{
return|return
literal|"test"
return|;
block|}
block|}
block|}
end_class

end_unit

