begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * This file is subject to the licence found in LICENCE.TXT in the root directory of the project.  * Copyright Jayasoft 2005 - All rights reserved  *   * #SNAPSHOT#  */
end_comment

begin_package
package|package
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|extendable
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_comment
comment|/**  * An item which is meant to be extended, i.e. defined using extra attributes  */
end_comment

begin_class
specifier|public
class|class
name|DefaultExtendableItem
extends|extends
name|UnmodifiableExtendableItem
block|{
specifier|public
name|DefaultExtendableItem
parameter_list|()
block|{
name|this
argument_list|(
literal|null
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
specifier|public
name|DefaultExtendableItem
parameter_list|(
name|Map
name|stdAttributes
parameter_list|,
name|Map
name|extraAttributes
parameter_list|)
block|{
name|super
argument_list|(
name|stdAttributes
argument_list|,
name|extraAttributes
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|setExtraAttribute
parameter_list|(
name|String
name|attName
parameter_list|,
name|String
name|attValue
parameter_list|)
block|{
name|super
operator|.
name|setExtraAttribute
argument_list|(
name|attName
argument_list|,
name|attValue
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|setStandardAttribute
parameter_list|(
name|String
name|attName
parameter_list|,
name|String
name|attValue
parameter_list|)
block|{
name|super
operator|.
name|setStandardAttribute
argument_list|(
name|attName
argument_list|,
name|attValue
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|setAttribute
parameter_list|(
name|String
name|attName
parameter_list|,
name|String
name|attValue
parameter_list|,
name|boolean
name|extra
parameter_list|)
block|{
name|super
operator|.
name|setAttribute
argument_list|(
name|attName
argument_list|,
name|attValue
argument_list|,
name|extra
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

