begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|resolve
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|cache
operator|.
name|CacheManager
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|event
operator|.
name|EventManager
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|settings
operator|.
name|IvySettings
import|;
end_import

begin_class
specifier|public
class|class
name|DownloadOptions
block|{
specifier|private
name|IvySettings
name|_settings
decl_stmt|;
specifier|private
name|CacheManager
name|_cacheManager
decl_stmt|;
specifier|private
name|EventManager
name|_eventManager
init|=
literal|null
decl_stmt|;
comment|// can be null
specifier|private
name|boolean
name|_useOrigin
init|=
literal|false
decl_stmt|;
specifier|public
name|DownloadOptions
parameter_list|(
name|IvySettings
name|settings
parameter_list|,
name|File
name|cache
parameter_list|)
block|{
name|this
argument_list|(
name|settings
argument_list|,
operator|new
name|CacheManager
argument_list|(
name|settings
argument_list|,
name|cache
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|DownloadOptions
parameter_list|(
name|IvySettings
name|settings
parameter_list|,
name|CacheManager
name|cacheManager
parameter_list|)
block|{
name|this
argument_list|(
name|settings
argument_list|,
name|cacheManager
argument_list|,
literal|null
argument_list|,
literal|false
argument_list|)
expr_stmt|;
block|}
specifier|public
name|DownloadOptions
parameter_list|(
name|IvySettings
name|settings
parameter_list|,
name|CacheManager
name|cacheManager
parameter_list|,
name|EventManager
name|eventManager
parameter_list|,
name|boolean
name|useOrigin
parameter_list|)
block|{
name|_settings
operator|=
name|settings
expr_stmt|;
name|_cacheManager
operator|=
name|cacheManager
expr_stmt|;
name|_eventManager
operator|=
name|eventManager
expr_stmt|;
name|_useOrigin
operator|=
name|useOrigin
expr_stmt|;
block|}
specifier|public
name|IvySettings
name|getSettings
parameter_list|()
block|{
return|return
name|_settings
return|;
block|}
specifier|public
name|boolean
name|isUseOrigin
parameter_list|()
block|{
return|return
name|_useOrigin
return|;
block|}
specifier|public
name|CacheManager
name|getCacheManager
parameter_list|()
block|{
return|return
name|_cacheManager
return|;
block|}
specifier|public
name|EventManager
name|getEventManager
parameter_list|()
block|{
return|return
name|_eventManager
return|;
block|}
block|}
end_class

end_unit

