begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * This file is subject to the licence found in LICENCE.TXT in the root directory of the project.  * Copyright Jayasoft 2005 - All rights reserved  *   * #SNAPSHOT#  */
end_comment

begin_package
package|package
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|event
operator|.
name|download
package|;
end_package

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|Artifact
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|ArtifactOrigin
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|DependencyResolver
import|;
end_import

begin_import
import|import
name|fr
operator|.
name|jayasoft
operator|.
name|ivy
operator|.
name|Ivy
import|;
end_import

begin_class
specifier|public
class|class
name|StartArtifactDownloadEvent
extends|extends
name|DownloadEvent
block|{
specifier|public
specifier|static
specifier|final
name|String
name|NAME
init|=
literal|"pre-download-artifact"
decl_stmt|;
specifier|private
name|DependencyResolver
name|_resolver
decl_stmt|;
specifier|private
name|ArtifactOrigin
name|_origin
decl_stmt|;
specifier|public
name|StartArtifactDownloadEvent
parameter_list|(
name|Ivy
name|source
parameter_list|,
name|DependencyResolver
name|resolver
parameter_list|,
name|Artifact
name|artifact
parameter_list|,
name|ArtifactOrigin
name|origin
parameter_list|)
block|{
name|super
argument_list|(
name|source
argument_list|,
name|NAME
argument_list|,
name|artifact
argument_list|)
expr_stmt|;
name|_resolver
operator|=
name|resolver
expr_stmt|;
name|_origin
operator|=
name|origin
expr_stmt|;
name|addAttribute
argument_list|(
literal|"resolver"
argument_list|,
name|_resolver
operator|.
name|getName
argument_list|()
argument_list|)
expr_stmt|;
name|addAttribute
argument_list|(
literal|"origin"
argument_list|,
name|origin
operator|.
name|getLocation
argument_list|()
argument_list|)
expr_stmt|;
name|addAttribute
argument_list|(
literal|"local"
argument_list|,
name|String
operator|.
name|valueOf
argument_list|(
name|origin
operator|.
name|isLocal
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|DependencyResolver
name|getResolver
parameter_list|()
block|{
return|return
name|_resolver
return|;
block|}
specifier|public
name|ArtifactOrigin
name|getOrigin
parameter_list|()
block|{
return|return
name|_origin
return|;
block|}
block|}
end_class

end_unit

