begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|ant
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|Ivy
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|TestHelper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|id
operator|.
name|ModuleRevisionId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|report
operator|.
name|ResolveReport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tools
operator|.
name|ant
operator|.
name|BuildException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tools
operator|.
name|ant
operator|.
name|Project
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|tools
operator|.
name|ant
operator|.
name|taskdefs
operator|.
name|Delete
import|;
end_import

begin_class
specifier|public
class|class
name|IvyResolveTest
extends|extends
name|TestCase
block|{
specifier|private
name|File
name|cache
decl_stmt|;
specifier|private
name|IvyResolve
name|resolve
decl_stmt|;
specifier|protected
name|void
name|setUp
parameter_list|()
throws|throws
name|Exception
block|{
name|createCache
argument_list|()
expr_stmt|;
name|Project
name|project
init|=
operator|new
name|Project
argument_list|()
decl_stmt|;
name|project
operator|.
name|setProperty
argument_list|(
literal|"ivy.settings.file"
argument_list|,
literal|"test/repositories/ivysettings.xml"
argument_list|)
expr_stmt|;
name|project
operator|.
name|setProperty
argument_list|(
literal|"ivy.cache.dir"
argument_list|,
name|cache
operator|.
name|getAbsolutePath
argument_list|()
argument_list|)
expr_stmt|;
name|resolve
operator|=
operator|new
name|IvyResolve
argument_list|()
expr_stmt|;
name|resolve
operator|.
name|setProject
argument_list|(
name|project
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|createCache
parameter_list|()
block|{
name|cache
operator|=
operator|new
name|File
argument_list|(
literal|"build/cache"
argument_list|)
expr_stmt|;
name|cache
operator|.
name|mkdirs
argument_list|()
expr_stmt|;
block|}
specifier|protected
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{
name|cleanCache
argument_list|()
expr_stmt|;
block|}
specifier|private
name|void
name|cleanCache
parameter_list|()
block|{
name|Delete
name|del
init|=
operator|new
name|Delete
argument_list|()
decl_stmt|;
name|del
operator|.
name|setProject
argument_list|(
operator|new
name|Project
argument_list|()
argument_list|)
expr_stmt|;
name|del
operator|.
name|setDir
argument_list|(
name|cache
argument_list|)
expr_stmt|;
name|del
operator|.
name|execute
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testIVY779
parameter_list|()
throws|throws
name|Exception
block|{
name|Project
name|project
init|=
operator|new
name|Project
argument_list|()
decl_stmt|;
name|project
operator|.
name|setProperty
argument_list|(
literal|"ivy.local.default.root"
argument_list|,
operator|new
name|File
argument_list|(
literal|"test/repositories/norev"
argument_list|)
operator|.
name|getAbsolutePath
argument_list|()
argument_list|)
expr_stmt|;
name|project
operator|.
name|setProperty
argument_list|(
literal|"ivy.local.default.ivy.pattern"
argument_list|,
literal|"[module]/[artifact].[ext]"
argument_list|)
expr_stmt|;
name|project
operator|.
name|setProperty
argument_list|(
literal|"ivy.local.default.artifact.pattern"
argument_list|,
literal|"[module]/[artifact].[ext]"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setProject
argument_list|(
name|project
argument_list|)
expr_stmt|;
name|project
operator|.
name|setProperty
argument_list|(
literal|"ivy.cache.dir"
argument_list|,
name|cache
operator|.
name|getAbsolutePath
argument_list|()
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/repositories/norev/ivy.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setKeep
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|ResolveReport
name|report
init|=
operator|(
name|ResolveReport
operator|)
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.report"
argument_list|)
decl_stmt|;
name|assertNotNull
argument_list|(
name|report
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|report
operator|.
name|hasError
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|report
operator|.
name|getArtifacts
argument_list|()
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testSimple
parameter_list|()
throws|throws
name|Exception
block|{
comment|// depends on org="org1" name="mod1.2" rev="2.0"
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getResolvedIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"apache"
argument_list|,
literal|"resolve-simple"
argument_list|,
literal|"1.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
comment|// dependencies
name|assertTrue
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testResolveWithoutIvyFile
parameter_list|()
throws|throws
name|Exception
block|{
comment|// IVY-630
name|resolve
operator|.
name|getProject
argument_list|()
operator|.
name|setProperty
argument_list|(
literal|"ivy.settings.file"
argument_list|,
literal|"test/repositories/IVY-630/ivysettings.xml"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-630.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setConf
argument_list|(
literal|"default"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setHaltonfailure
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"junit"
argument_list|,
literal|"junit"
argument_list|,
literal|"4.1"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"junit"
argument_list|,
literal|"junit"
argument_list|,
literal|"4.1"
argument_list|,
literal|"junit"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|private
name|File
name|getArchiveFileInCache
parameter_list|(
name|String
name|organisation
parameter_list|,
name|String
name|module
parameter_list|,
name|String
name|revision
parameter_list|,
name|String
name|artifact
parameter_list|,
name|String
name|type
parameter_list|,
name|String
name|ext
parameter_list|)
block|{
return|return
name|TestHelper
operator|.
name|getArchiveFileInCache
argument_list|(
name|getIvy
argument_list|()
argument_list|,
name|organisation
argument_list|,
name|module
argument_list|,
name|revision
argument_list|,
name|artifact
argument_list|,
name|type
argument_list|,
name|ext
argument_list|)
return|;
block|}
specifier|private
name|File
name|getIvyFileInCache
parameter_list|(
name|ModuleRevisionId
name|id
parameter_list|)
block|{
return|return
name|TestHelper
operator|.
name|getRepositoryCacheManager
argument_list|(
name|getIvy
argument_list|()
argument_list|,
name|id
argument_list|)
operator|.
name|getIvyFileInCache
argument_list|(
name|id
argument_list|)
return|;
block|}
specifier|private
name|File
name|getResolvedIvyFileInCache
parameter_list|(
name|ModuleRevisionId
name|id
parameter_list|)
block|{
return|return
name|getIvy
argument_list|()
operator|.
name|getResolutionCacheManager
argument_list|()
operator|.
name|getResolvedIvyFileInCache
argument_list|(
name|id
argument_list|)
return|;
block|}
specifier|public
name|void
name|testInline
parameter_list|()
throws|throws
name|Exception
block|{
comment|// same as before, but expressing dependency directly without ivy file
name|resolve
operator|.
name|setOrganisation
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setModule
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setRevision
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setInline
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// dependencies
name|assertTrue
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testInlineWithResolveId
parameter_list|()
throws|throws
name|Exception
block|{
comment|// same as before, but expressing dependency directly without ivy file
name|resolve
operator|.
name|setOrganisation
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setModule
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setRevision
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setInline
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setResolveId
argument_list|(
literal|"testInlineWithResolveId"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setKeep
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// dependencies
name|assertTrue
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testInlineForNonExistingModule
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setOrganisation
argument_list|(
literal|"org1XX"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setModule
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setRevision
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setInline
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setHaltonfailure
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setFailureProperty
argument_list|(
literal|"failure.property"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// the resolve must have failed -> the failure property must be set
name|String
name|failure
init|=
name|resolve
operator|.
name|getProject
argument_list|()
operator|.
name|getProperty
argument_list|(
literal|"failure.property"
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"Failure property must have been specified!"
argument_list|,
name|Boolean
operator|.
name|valueOf
argument_list|(
name|failure
argument_list|)
operator|.
name|booleanValue
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testWithSlashes
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/core/resolve/ivy-198.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|File
name|resolvedIvyFileInCache
init|=
name|getResolvedIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"myorg/mydep"
argument_list|,
literal|"system/module"
argument_list|,
literal|"1.0"
argument_list|)
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|resolvedIvyFileInCache
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
comment|// dependencies
name|assertTrue
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"yourorg/yourdep"
argument_list|,
literal|"yoursys/yourmod"
argument_list|,
literal|"1.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"yourorg/yourdep"
argument_list|,
literal|"yoursys/yourmod"
argument_list|,
literal|"1.0"
argument_list|,
literal|"yourmod"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testDepsChanged
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
literal|"true"
argument_list|,
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
literal|"false"
argument_list|,
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testDontCheckIfChanged
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setCheckIfChanged
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertNull
argument_list|(
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertNull
argument_list|(
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
comment|//To be complete, we should also check that the XmlReportParser is not invoked
comment|//but this would require a too big refactoring to inject a mock object
block|}
specifier|public
name|void
name|testConflictingDepsChanged
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/repositories/2/mod4.1/ivy-4.1.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
literal|"true"
argument_list|,
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
literal|"false"
argument_list|,
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testDouble
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
literal|"resolve-simple"
argument_list|,
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.module"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"1.0"
argument_list|,
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.revision"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-double.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
literal|"resolve-double"
argument_list|,
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.module"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"1.1"
argument_list|,
name|getIvy
argument_list|()
operator|.
name|getVariable
argument_list|(
literal|"ivy.revision"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testFailure
parameter_list|()
throws|throws
name|Exception
block|{
try|try
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-failure.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|fail
argument_list|(
literal|"failure didn't raised an exception with default haltonfailure setting"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|BuildException
name|ex
parameter_list|)
block|{
comment|// ok => should raise an exception
block|}
block|}
specifier|public
name|void
name|testIvyLogModulesInUseWithFailure
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|getProject
argument_list|()
operator|.
name|setProperty
argument_list|(
literal|"ivy.log.modules.in.use"
argument_list|,
literal|"true"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-failure.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setHaltonfailure
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// we did manage to get here, so no NPE has been thrown (IVY-961)
block|}
specifier|public
name|void
name|testFailureWithMissingConfigurations
parameter_list|()
throws|throws
name|Exception
block|{
try|try
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setConf
argument_list|(
literal|"default,unknown"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|fail
argument_list|(
literal|"missing configurations didn't raised an exception"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|BuildException
name|ex
parameter_list|)
block|{
name|assertTrue
argument_list|(
name|ex
operator|.
name|getMessage
argument_list|()
operator|.
name|indexOf
argument_list|(
literal|"unknown"
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|testFailureOnBadDependencyIvyFile
parameter_list|()
throws|throws
name|Exception
block|{
try|try
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-failure2.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|fail
argument_list|(
literal|"failure didn't raised an exception with default haltonfailure setting"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|BuildException
name|ex
parameter_list|)
block|{
comment|// ok => should raise an exception
block|}
block|}
specifier|public
name|void
name|testFailureOnBadStatusInDependencyIvyFile
parameter_list|()
throws|throws
name|Exception
block|{
try|try
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-failure3.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|fail
argument_list|(
literal|"failure didn't raised an exception with default haltonfailure setting"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|BuildException
name|ex
parameter_list|)
block|{
comment|// ok => should raise an exception
block|}
block|}
specifier|public
name|void
name|testHaltOnFailure
parameter_list|()
throws|throws
name|Exception
block|{
try|try
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-failure.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setHaltonfailure
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|BuildException
name|ex
parameter_list|)
block|{
name|ex
operator|.
name|printStackTrace
argument_list|()
expr_stmt|;
name|fail
argument_list|(
literal|"failure raised an exception with haltonfailure set to false"
argument_list|)
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|testWithResolveId
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setResolveId
argument_list|(
literal|"testWithResolveId"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getResolvedIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"apache"
argument_list|,
literal|"resolve-simple"
argument_list|,
literal|"1.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getIvy
argument_list|()
operator|.
name|getResolutionCacheManager
argument_list|()
operator|.
name|getConfigurationResolveReportInCache
argument_list|(
literal|"testWithResolveId"
argument_list|,
literal|"default"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
comment|// dependencies
name|assertTrue
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
comment|// test the properties
name|Project
name|project
init|=
name|resolve
operator|.
name|getProject
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|"apache"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.organisation"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"apache"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.organisation.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"resolve-simple"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.module"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"resolve-simple"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.module.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"1.0"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.revision"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"1.0"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.revision.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"true"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"true"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.deps.changed.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"default"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.resolved.configurations"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"default"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.resolved.configurations.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
comment|// test the references
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.report"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.report.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.descriptor"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.descriptor.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.configurations.ref"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.configurations.ref.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testDoubleResolveWithResolveId
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setResolveId
argument_list|(
literal|"testWithResolveId"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|IvyResolve
name|newResolve
init|=
operator|new
name|IvyResolve
argument_list|()
decl_stmt|;
name|newResolve
operator|.
name|setProject
argument_list|(
name|resolve
operator|.
name|getProject
argument_list|()
argument_list|)
expr_stmt|;
name|newResolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple2.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|newResolve
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// test the properties
name|Project
name|project
init|=
name|resolve
operator|.
name|getProject
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|"apache2"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.organisation"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"apache"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.organisation.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"resolve-simple2"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.module"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"resolve-simple"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.module.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"1.1"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.revision"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"1.0"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.revision.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"true"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"true"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.deps.changed.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"default"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.resolved.configurations"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"default"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.resolved.configurations.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
comment|// test the references
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.report"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.report.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.descriptor"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.descriptor.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.configurations.ref"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.configurations.ref.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testDifferentResolveWithSameResolveId
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setResolveId
argument_list|(
literal|"testWithResolveId"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|IvyResolve
name|newResolve
init|=
operator|new
name|IvyResolve
argument_list|()
decl_stmt|;
name|newResolve
operator|.
name|setProject
argument_list|(
name|resolve
operator|.
name|getProject
argument_list|()
argument_list|)
expr_stmt|;
name|newResolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple2.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|newResolve
operator|.
name|setResolveId
argument_list|(
literal|"testWithResolveId"
argument_list|)
expr_stmt|;
name|newResolve
operator|.
name|execute
argument_list|()
expr_stmt|;
comment|// test the properties
name|Project
name|project
init|=
name|resolve
operator|.
name|getProject
argument_list|()
decl_stmt|;
name|assertEquals
argument_list|(
literal|"apache2"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.organisation"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"apache2"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.organisation.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"resolve-simple2"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.module"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"resolve-simple2"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.module.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"1.1"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.revision"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"1.1"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.revision.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"true"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.deps.changed"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"true"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.deps.changed.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"default"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.resolved.configurations"
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"default"
argument_list|,
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.resolved.configurations.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
comment|// test the references
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.report"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.report.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.descriptor"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.descriptor.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.configurations.ref"
argument_list|)
argument_list|)
expr_stmt|;
name|assertNotNull
argument_list|(
name|project
operator|.
name|getReference
argument_list|(
literal|"ivy.resolved.configurations.ref.testWithResolveId"
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testExcludedConf
parameter_list|()
throws|throws
name|Exception
block|{
name|resolve
operator|.
name|setFile
argument_list|(
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-multiconf.xml"
argument_list|)
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|setConf
argument_list|(
literal|"*,!default"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.1"
argument_list|,
literal|"2.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|getIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
comment|// test the properties
name|Project
name|project
init|=
name|resolve
operator|.
name|getProject
argument_list|()
decl_stmt|;
name|assertFalse
argument_list|(
name|project
operator|.
name|getProperty
argument_list|(
literal|"ivy.resolved.configurations"
argument_list|)
operator|.
name|indexOf
argument_list|(
literal|"default"
argument_list|)
operator|>
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testResolveWithAbsoluteFile
parameter_list|()
block|{
comment|// IVY-396
name|File
name|ivyFile
init|=
operator|new
name|File
argument_list|(
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
decl_stmt|;
name|resolve
operator|.
name|getProject
argument_list|()
operator|.
name|setProperty
argument_list|(
literal|"ivy.dep.file"
argument_list|,
name|ivyFile
operator|.
name|getAbsolutePath
argument_list|()
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getResolvedIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"apache"
argument_list|,
literal|"resolve-simple"
argument_list|,
literal|"1.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testResolveWithRelativeFile
parameter_list|()
block|{
comment|// IVY-396
name|resolve
operator|.
name|getProject
argument_list|()
operator|.
name|setProperty
argument_list|(
literal|"ivy.dep.file"
argument_list|,
literal|"test/java/org/apache/ivy/ant/ivy-simple.xml"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getResolvedIvyFileInCache
argument_list|(
name|ModuleRevisionId
operator|.
name|newInstance
argument_list|(
literal|"apache"
argument_list|,
literal|"resolve-simple"
argument_list|,
literal|"1.0"
argument_list|)
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|private
name|Ivy
name|getIvy
parameter_list|()
block|{
return|return
name|resolve
operator|.
name|getIvyInstance
argument_list|()
return|;
block|}
specifier|public
name|void
name|testChildsSimple
parameter_list|()
throws|throws
name|Exception
block|{
name|IvyDependency
name|dependency
init|=
name|resolve
operator|.
name|createDependency
argument_list|()
decl_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testChildsMultiple
parameter_list|()
throws|throws
name|Exception
block|{
name|IvyDependency
name|dependency
init|=
name|resolve
operator|.
name|createDependency
argument_list|()
decl_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|dependency
operator|=
name|resolve
operator|.
name|createDependency
argument_list|()
expr_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod2.3"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"0.7"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.3"
argument_list|,
literal|"0.7"
argument_list|,
literal|"mod2.3"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"0.3"
argument_list|,
literal|"art21A"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"0.3"
argument_list|,
literal|"art21B"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.1"
argument_list|,
literal|"1.0"
argument_list|,
literal|"mod1.1"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testChildsMultipleWithConf
parameter_list|()
throws|throws
name|Exception
block|{
name|IvyDependency
name|dependency
init|=
name|resolve
operator|.
name|createDependency
argument_list|()
decl_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|dependency
operator|=
name|resolve
operator|.
name|createDependency
argument_list|()
expr_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod2.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"0.10"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setConf
argument_list|(
literal|"A"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"0.10"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"0.7"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testChildsMultipleWithConf2
parameter_list|()
throws|throws
name|Exception
block|{
name|IvyDependency
name|dependency
init|=
name|resolve
operator|.
name|createDependency
argument_list|()
decl_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|dependency
operator|=
name|resolve
operator|.
name|createDependency
argument_list|()
expr_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod2.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"0.10"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setConf
argument_list|(
literal|"B"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"0.10"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"0.7"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.1"
argument_list|,
literal|"1.0"
argument_list|,
literal|"mod1.1"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testChildsExclude
parameter_list|()
throws|throws
name|Exception
block|{
name|IvyDependency
name|dependency
init|=
name|resolve
operator|.
name|createDependency
argument_list|()
decl_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|dependency
operator|=
name|resolve
operator|.
name|createDependency
argument_list|()
expr_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod2.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"0.10"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setConf
argument_list|(
literal|"B"
argument_list|)
expr_stmt|;
name|IvyExclude
name|exclude
init|=
name|resolve
operator|.
name|createExclude
argument_list|()
decl_stmt|;
name|exclude
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|exclude
operator|.
name|setModule
argument_list|(
literal|"mod1.1"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"0.10"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"0.7"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testChildsDependencyExclude
parameter_list|()
throws|throws
name|Exception
block|{
name|IvyDependency
name|dependency
init|=
name|resolve
operator|.
name|createDependency
argument_list|()
decl_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|dependency
operator|=
name|resolve
operator|.
name|createDependency
argument_list|()
expr_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod2.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"0.10"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setConf
argument_list|(
literal|"B"
argument_list|)
expr_stmt|;
name|IvyDependencyExclude
name|exclude
init|=
name|dependency
operator|.
name|createExclude
argument_list|()
decl_stmt|;
name|exclude
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"0.10"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"0.7"
argument_list|,
literal|"mod2.1"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testChildsDependencyInclude
parameter_list|()
throws|throws
name|Exception
block|{
name|IvyDependency
name|dependency
init|=
name|resolve
operator|.
name|createDependency
argument_list|()
decl_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod1.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
name|dependency
operator|=
name|resolve
operator|.
name|createDependency
argument_list|()
expr_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"mod2.2"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"0.9"
argument_list|)
expr_stmt|;
name|IvyDependencyInclude
name|include
init|=
name|dependency
operator|.
name|createInclude
argument_list|()
decl_stmt|;
name|include
operator|.
name|setName
argument_list|(
literal|"art22-1"
argument_list|)
expr_stmt|;
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org1"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"2.0"
argument_list|,
literal|"mod1.2"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|getArchiveFileInCache
argument_list|(
literal|"org2"
argument_list|,
literal|"mod2.2"
argument_list|,
literal|"0.9"
argument_list|,
literal|"art22-1"
argument_list|,
literal|"jar"
argument_list|,
literal|"jar"
argument_list|)
operator|.
name|exists
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testChildsFail
parameter_list|()
throws|throws
name|Exception
block|{
name|IvyDependency
name|dependency
init|=
name|resolve
operator|.
name|createDependency
argument_list|()
decl_stmt|;
name|dependency
operator|.
name|setOrg
argument_list|(
literal|"org1"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setName
argument_list|(
literal|"noexisting"
argument_list|)
expr_stmt|;
name|dependency
operator|.
name|setRev
argument_list|(
literal|"2.0"
argument_list|)
expr_stmt|;
try|try
block|{
name|resolve
operator|.
name|execute
argument_list|()
expr_stmt|;
name|fail
argument_list|(
literal|"A fail resolved should have raised a build exception"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|BuildException
name|e
parameter_list|)
block|{
comment|// ok
block|}
block|}
block|}
end_class

end_unit

