begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      https://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|plugins
operator|.
name|version
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|core
operator|.
name|module
operator|.
name|id
operator|.
name|ModuleRevisionId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|plugins
operator|.
name|matcher
operator|.
name|Matcher
import|;
end_import

begin_comment
comment|/**  *  */
end_comment

begin_class
specifier|public
class|class
name|PatternVersionMatcher
extends|extends
name|AbstractVersionMatcher
block|{
specifier|private
specifier|final
name|List
argument_list|<
name|Match
argument_list|>
name|matches
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
specifier|private
specifier|final
name|Map
argument_list|<
name|String
argument_list|,
name|List
argument_list|<
name|Match
argument_list|>
argument_list|>
name|revisionMatches
init|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
decl_stmt|;
comment|// revision -> list of Match instances
specifier|private
name|boolean
name|init
init|=
literal|false
decl_stmt|;
specifier|public
name|void
name|addMatch
parameter_list|(
name|Match
name|match
parameter_list|)
block|{
name|matches
operator|.
name|add
argument_list|(
name|match
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|init
parameter_list|()
block|{
if|if
condition|(
operator|!
name|init
condition|)
block|{
for|for
control|(
name|Match
name|match
range|:
name|matches
control|)
block|{
name|List
argument_list|<
name|Match
argument_list|>
name|revMatches
init|=
name|revisionMatches
operator|.
name|get
argument_list|(
name|match
operator|.
name|getRevision
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|revMatches
operator|==
literal|null
condition|)
block|{
name|revMatches
operator|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
expr_stmt|;
name|revisionMatches
operator|.
name|put
argument_list|(
name|match
operator|.
name|getRevision
argument_list|()
argument_list|,
name|revMatches
argument_list|)
expr_stmt|;
block|}
name|revMatches
operator|.
name|add
argument_list|(
name|match
argument_list|)
expr_stmt|;
block|}
name|init
operator|=
literal|true
expr_stmt|;
block|}
block|}
comment|/**      * {@inheritDoc}      */
specifier|public
name|boolean
name|accept
parameter_list|(
name|ModuleRevisionId
name|askedMrid
parameter_list|,
name|ModuleRevisionId
name|foundMrid
parameter_list|)
block|{
name|init
argument_list|()
expr_stmt|;
name|boolean
name|accept
init|=
literal|false
decl_stmt|;
name|String
name|revision
init|=
name|askedMrid
operator|.
name|getRevision
argument_list|()
decl_stmt|;
name|int
name|bracketIndex
init|=
name|revision
operator|.
name|indexOf
argument_list|(
literal|'('
argument_list|)
decl_stmt|;
if|if
condition|(
name|bracketIndex
operator|>
literal|0
condition|)
block|{
name|revision
operator|=
name|revision
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
name|bracketIndex
argument_list|)
expr_stmt|;
block|}
name|List
argument_list|<
name|Match
argument_list|>
name|revMatches
init|=
name|revisionMatches
operator|.
name|get
argument_list|(
name|revision
argument_list|)
decl_stmt|;
if|if
condition|(
name|revMatches
operator|!=
literal|null
condition|)
block|{
for|for
control|(
name|Match
name|match
range|:
name|revMatches
control|)
block|{
name|Matcher
name|matcher
init|=
name|match
operator|.
name|getPatternMatcher
argument_list|(
name|askedMrid
argument_list|)
decl_stmt|;
name|accept
operator|=
name|matcher
operator|.
name|matches
argument_list|(
name|foundMrid
operator|.
name|getRevision
argument_list|()
argument_list|)
expr_stmt|;
if|if
condition|(
name|accept
condition|)
block|{
break|break;
block|}
block|}
block|}
return|return
name|accept
return|;
block|}
comment|/**      * {@inheritDoc}      */
specifier|public
name|boolean
name|isDynamic
parameter_list|(
name|ModuleRevisionId
name|askedMrid
parameter_list|)
block|{
name|init
argument_list|()
expr_stmt|;
name|String
name|revision
init|=
name|askedMrid
operator|.
name|getRevision
argument_list|()
decl_stmt|;
name|int
name|bracketIndex
init|=
name|revision
operator|.
name|indexOf
argument_list|(
literal|'('
argument_list|)
decl_stmt|;
if|if
condition|(
name|bracketIndex
operator|>
literal|0
condition|)
block|{
name|revision
operator|=
name|revision
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
name|bracketIndex
argument_list|)
expr_stmt|;
block|}
return|return
name|revisionMatches
operator|.
name|containsKey
argument_list|(
name|revision
argument_list|)
return|;
block|}
block|}
end_class

end_unit

