begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  *  Licensed to the Apache Software Foundation (ASF) under one or more  *  contributor license agreements.  See the NOTICE file distributed with  *  this work for additional information regarding copyright ownership.  *  The ASF licenses this file to You under the Apache License, Version 2.0  *  (the "License"); you may not use this file except in compliance with  *  the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  *  Unless required by applicable law or agreed to in writing, software  *  distributed under the License is distributed on an "AS IS" BASIS,  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  See the License for the specific language governing permissions and  *  limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|ivy
operator|.
name|util
package|;
end_package

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_class
specifier|public
class|class
name|StringUtilsTest
extends|extends
name|TestCase
block|{
specifier|public
name|void
name|testGetStackTrace
parameter_list|()
throws|throws
name|Exception
block|{
name|String
name|trace
init|=
name|StringUtils
operator|.
name|getStackTrace
argument_list|(
operator|new
name|Exception
argument_list|()
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|trace
operator|.
name|indexOf
argument_list|(
literal|"java.lang.Exception"
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|trace
operator|.
name|indexOf
argument_list|(
literal|"at org.apache.ivy.util.StringUtilsTest.testGetStackTrace(StringUtilsTest.java"
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testEncryption
parameter_list|()
block|{
name|assertEquals
argument_list|(
literal|"apache"
argument_list|,
name|StringUtils
operator|.
name|decrypt
argument_list|(
name|StringUtils
operator|.
name|encrypt
argument_list|(
literal|"apache"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
literal|"yet another string with 126 digits and others :;%_-$& characters"
argument_list|,
name|StringUtils
operator|.
name|decrypt
argument_list|(
name|StringUtils
operator|.
name|encrypt
argument_list|(
literal|"yet another string with 126 digits and others :;%_-$& characters"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
literal|"apache"
operator|.
name|equals
argument_list|(
name|StringUtils
operator|.
name|encrypt
argument_list|(
literal|"apache"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

